name: Unit Tests

on:
  push:

jobs:
  units-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'

      - name: Install Dependencies
        run: flutter pub get

      - name: Create .env file
        run: echo "TRELLO_API_KEY=${{ secrets.TRELLO_API_KEY }}" >> .env && echo "TRELLO_APP_NAME=${{ secrets.TRELLO_APP_NAME }}" >> .env

      - name: Generate Localizations
        run: flutter gen-l10n

      - name: Run Tests
        run: flutter test

  integration-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 34 ]
        target: [ playstore ]
    needs: units-tests
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.1'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Create .env file
        run: echo "TRELLO_API_KEY=${{ secrets.TRELLO_API_KEY }}" >> .env && echo "TRELLO_APP_NAME=${{ secrets.TRELLO_APP_NAME }}" >> .env

      - name: Generate Localizations
        run: flutter gen-l10n

      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: ${{ matrix.target }}
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter drive --driver=integration_test/

          # Update screenshot to artifact
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: screenshot
          path: ${{ matrix.path }}screenshots/
