name: Generate and Deploy DartDoc

on: push

jobs:
  generate-documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.1'

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install DartDoc
        run: dart pub global activate dartdoc

      - name: Generate DartDoc
        run: dart pub global run dartdoc