name: Generate and Deploy DartDoc

on: push

jobs:
  generate-documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.1'

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install DartDoc
        run: dart pub global activate dartdoc

      - name: Generate DartDoc
        run: dart pub global run dartdoc

      - name: Deploy to Mirror Repository
        run: |
          git config --global user.name 'eloiJhn'
          git config --global user.email 'eloi.jahan9221@gmail.com'
          git clone git@github.com:EpitechMscProPromo2026/T-DEV-600-NAN_2.git
          cp -r doc/* documentation/
          cd documentation
          git add .
          git commit -m "Update documentation"
          git push